# Analysis of Image Preprocessing Experiments Results

In [4]:
# Import libraries
import pandas as pd
import numpy as np

In [5]:
# Load the results csv in a dataframe
results_df = pd.read_csv('image_preprocessing_results.csv')

## Custom CNN

In [ ]:
# Custom CNN all results
custom_cnn = results_df[results_df['model'] == 'Custom CNN']

In [ ]:
# Get Image preprocessing pipelines with max performances
max_auc_custom_cnn = custom_cnn[custom_cnn['auc'] == custom_cnn['auc'].max()]['image_preprocessing_pipeline']
max_sencitivity_custom_cnn = custom_cnn[custom_cnn['sensitivity'] == custom_cnn['sensitivity'].max()]['image_preprocessing_pipeline']
max_specificity_custom_cnn = custom_cnn[custom_cnn['specificity'] == custom_cnn['specificity'].max()]['image_preprocessing_pipeline']
max_precision_custom_cnn = custom_cnn[custom_cnn['precision'] == custom_cnn['precision'].max()]['image_preprocessing_pipeline']
max_f1_custom_cnn = custom_cnn[custom_cnn['f1_score'] == custom_cnn['f1_score'].max()]['image_preprocessing_pipeline']

# Get Image Preprocessing Pipelines with least computational costs
min_training_time_custom_cnn = custom_cnn[custom_cnn['training_time_mins'] == custom_cnn['training_time_mins'].min()]['image_preprocessing_pipeline']
min_prediction_time_custom_cnn = custom_cnn[custom_cnn['prediction_time_sec'] == custom_cnn['prediction_time_sec'].min()]['image_preprocessing_pipeline']
min_peak_memory_custom_cnn = custom_cnn[custom_cnn['peak_memory_used_MB'] == custom_cnn['peak_memory_used_MB'].min()]['image_preprocessing_pipeline']

In [ ]:
print(f"Max AUC:")
print(max_auc_custom_cnn)

print(f"Max Sensitivity:")
print(max_sencitivity_custom_cnn)

print(f"Max Specificity:")
print(max_specificity_custom_cnn)

print(f"Max Precision:")
print(max_precision_custom_cnn)

print(f"Max F1 Score:")
print(max_f1_custom_cnn)

print(f"Min Training Time (minutes):")
print(min_training_time_custom_cnn)

print(f"Min Prediction Time (seconds):")
print(min_prediction_time_custom_cnn)

print(f"Min Peak Memory (MB):")
print(min_peak_memory_custom_cnn)

Max AUC:
16    P4
24    P6
Name: image_preprocessing_pipeline, dtype: object
Max Sensitivity:
8    P2
Name: image_preprocessing_pipeline, dtype: object
Max Specificity:
12     P3
20     P5
28     P7
36     P9
40    P10
Name: image_preprocessing_pipeline, dtype: object
Max Precision:
16    P4
24    P6
Name: image_preprocessing_pipeline, dtype: object
Max F1 Score:
8    P2
Name: image_preprocessing_pipeline, dtype: object
Min Training Time (minutes):
16    P4
Name: image_preprocessing_pipeline, dtype: object
Min Prediction Time (seconds):
16    P4
Name: image_preprocessing_pipeline, dtype: object
Min Peak Memory (MB):
36    P9
Name: image_preprocessing_pipeline, dtype: object

### Inference for Custom CNN

* Max AUC: P4, P6
* Max Sensitivity: P2
* Max Precision: P4, P6
* Max F1-Score: P2
* Max Specificity: P3, P5, P7, P9, P10
* Min Training-Time: P4
* Min Prediction-Time: P4
* Min Peak Memory used: P9

Overall,
1. P2 attains max sensitivity and F1 Score.
2. P4 attains max AUC, Precision with minimum training and prediction time
3. P9 attains max specificity with minimum peak memory usage.

In [ ]:
custom_cnn[custom_cnn['image_preprocessing_pipeline'].isin(['P2', 'P4', 'P9'])]

,model,view,image_preprocessing_pipeline,accuracy,auc,sensitivity,precision,specificity,f1_score,training_time_mins,prediction_time_sec,peak_memory_used_MB,parameters
8,Custom CNN,View_Independent,P2,0.575284,0.603070,0.357143,0.555556,0.704188,0.434783,20.618057,3.944719,1767.961182,9724449
16,Custom CNN,View_Independent,P4,0.552557,0.640069,0.093168,0.566038,0.937173,0.160000,16.918803,3.080129,1767.961182,9724449
36,Custom CNN,View_Independent,P9,0.542614,0.635435,0.000000,0.000000,1.000000,0.000000,18.949348,5.198756,1767.960938,9724449

### Result for Custom CNN
P2 and P4 have negligible difference in accuracy, AUC, precision, prediction time and peak memory usage values. However, P2 achieves significantly higher sensitivity, f1 score and training time (4 minutes more than P4).  

P9 achieves significantly lower sensitivity, precision and f1 scores with higher training and prediction times. Therefore, P9 can be eliminated.

Regardless of slightly higher training time, P2 demonstrates overall better performance across all metrics.

**Best Image Preprocessing Pipeline for Custom CNN: P2 (Resizing + CLAHE with 1-channel Grayscale + Normalization)**

## VGG16

In [6]:
# VGG16 all results
vgg16 = results_df[results_df['model'] == 'VGG16']

In [7]:
# Get Image preprocessing pipelines with max performances
max_auc_vgg16 = vgg16[vgg16['auc'] == vgg16['auc'].max()]['image_preprocessing_pipeline']
max_sencitivity_vgg16 = vgg16[vgg16['sensitivity'] == vgg16['sensitivity'].max()]['image_preprocessing_pipeline']
max_specificity_vgg16 = vgg16[vgg16['specificity'] == vgg16['specificity'].max()]['image_preprocessing_pipeline']
max_precision_vgg16 = vgg16[vgg16['precision'] == vgg16['precision'].max()]['image_preprocessing_pipeline']
max_f1_vgg16 = vgg16[vgg16['f1_score'] == vgg16['f1_score'].max()]['image_preprocessing_pipeline']

# Get Image Preprocessing Pipelines with least computational costs
min_training_time_vgg16 = vgg16[vgg16['training_time_mins'] == vgg16['training_time_mins'].min()]['image_preprocessing_pipeline']
min_prediction_time_vgg16 = vgg16[vgg16['prediction_time_sec'] == vgg16['prediction_time_sec'].min()]['image_preprocessing_pipeline']
min_peak_memory_vgg16 = vgg16[vgg16['peak_memory_used_MB'] == vgg16['peak_memory_used_MB'].min()]['image_preprocessing_pipeline']

In [8]:
print(f"Max AUC:")
print(max_auc_vgg16)

print(f"Max Sensitivity:")
print(max_sencitivity_vgg16)

print(f"Max Specificity:")
print(max_specificity_vgg16)

print(f"Max Precision:")
print(max_precision_vgg16)

print(f"Max F1 Score:")
print(max_f1_vgg16)

print(f"Min Training Time (minutes):")
print(min_training_time_vgg16)

print(f"Min Prediction Time (seconds):")
print(min_prediction_time_vgg16)

print(f"Min Peak Memory (MB):")
print(min_peak_memory_vgg16)

Max AUC:
9    P2
Name: image_preprocessing_pipeline, dtype: object
Max Sensitivity:
1      P0
5      P1
9      P2
13     P3
17     P4
21     P5
25     P6
29     P7
33     P8
37     P9
41    P10
Name: image_preprocessing_pipeline, dtype: object
Max Specificity:
1      P0
5      P1
9      P2
13     P3
17     P4
21     P5
25     P6
29     P7
33     P8
37     P9
41    P10
Name: image_preprocessing_pipeline, dtype: object
Max Precision:
1      P0
5      P1
9      P2
13     P3
17     P4
21     P5
25     P6
29     P7
33     P8
37     P9
41    P10
Name: image_preprocessing_pipeline, dtype: object
Max F1 Score:
1      P0
5      P1
9      P2
13     P3
17     P4
21     P5
25     P6
29     P7
33     P8
37     P9
41    P10
Name: image_preprocessing_pipeline, dtype: object
Min Training Time (minutes):
25    P6
Name: image_preprocessing_pipeline, dtype: object
Min Prediction Time (seconds):
25    P6
Name: image_preprocessing_pipeline, dtype: object
Min Peak Memory (MB):
1      P0
5      P1
9      P2
13     P3
17     P4
21     P5
25     P6
29     P7
33     P8
37     P9
41    P10
Name: image_preprocessing_pipeline, dtype: object

### Inference for VGG16

* Max AUC: P2
* Max Sensitivity: P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10
* Max Precision: P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10
* Max F1-Score: P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10
* Max Specificity: P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10
* Min Training-Time: P6
* Min Prediction-Time: P6
* Min Peak Memory used: P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10

Overall,
1. P2 attains max AUC.
2. P6 attains minimum training and prediction times.
3. All pipelines attain the same sensitivity, precision, f1-score, specificity and peak memory usage values.

In [9]:
vgg16[vgg16['image_preprocessing_pipeline'].isin(['P2', 'P6'])]

,model,view,image_preprocessing_pipeline,accuracy,auc,sensitivity,precision,specificity,f1_score,training_time_mins,prediction_time_sec,peak_memory_used_MB,parameters
9,VGG16,View_Independent,P2,0.542614,0.541178,0.0,0.0,1.0,0.0,19.869997,6.476736,3285.903564,14715201
25,VGG16,View_Independent,P6,0.542614,0.503927,0.0,0.0,1.0,0.0,19.049172,6.143839,3285.903564,14715201

### Result for VGG16
All pipelines have the same accuracy, sensitivity, precision, specificity, f1 score and peak memory usage values. Out of P2 and P6, it is evident that P2 attains slightly higher AUC score with negligibly higher training and prediction times compared to P6.  

**Best Image Preprocessing Pipeline for VGG16: P2 (Resizing + CLAHE with 1-channel Grayscale + Normalization)**

## ResNet50

In [10]:
# ResNet50 all results
resnet50 = results_df[results_df['model'] == 'ResNet50']

In [11]:
# Get Image preprocessing pipelines with max performances
max_auc_resnet50 = resnet50[resnet50['auc'] == resnet50['auc'].max()]['image_preprocessing_pipeline']
max_sencitivity_resnet50 = resnet50[resnet50['sensitivity'] == resnet50['sensitivity'].max()]['image_preprocessing_pipeline']
max_specificity_resnet50 = resnet50[resnet50['specificity'] == resnet50['specificity'].max()]['image_preprocessing_pipeline']
max_precision_resnet50 = resnet50[resnet50['precision'] == resnet50['precision'].max()]['image_preprocessing_pipeline']
max_f1_resnet50 = resnet50[resnet50['f1_score'] == resnet50['f1_score'].max()]['image_preprocessing_pipeline']

# Get Image Preprocessing Pipelines with least computational costs
min_training_time_resnet50 = resnet50[resnet50['training_time_mins'] == resnet50['training_time_mins'].min()]['image_preprocessing_pipeline']
min_prediction_time_resnet50 = resnet50[resnet50['prediction_time_sec'] == resnet50['prediction_time_sec'].min()]['image_preprocessing_pipeline']
min_peak_memory_resnet50 = resnet50[resnet50['peak_memory_used_MB'] == resnet50['peak_memory_used_MB'].min()]['image_preprocessing_pipeline']

In [14]:
print(f"Max AUC:")
print(max_auc_resnet50)

print(f"Max Sensitivity:")
print(max_sencitivity_resnet50)

print(f"Max Specificity:")
print(max_specificity_resnet50)

print(f"Max Precision:")
print(max_precision_resnet50)

print(f"Max F1 Score:")
print(max_f1_resnet50)

print(f"Min Training Time (minutes):")
print(min_training_time_resnet50)

print(f"Min Prediction Time (seconds):")
print(min_prediction_time_resnet50)

print(f"Min Peak Memory (MB):")
print(min_peak_memory_resnet50)

Max AUC:
18    P4
26    P6
Name: image_preprocessing_pipeline, dtype: object
Max Sensitivity:
2      P0
6      P1
10     P2
14     P3
18     P4
22     P5
26     P6
30     P7
34     P8
38     P9
42    P10
Name: image_preprocessing_pipeline, dtype: object
Max Specificity:
2      P0
6      P1
10     P2
14     P3
18     P4
22     P5
26     P6
30     P7
34     P8
38     P9
42    P10
Name: image_preprocessing_pipeline, dtype: object
Max Precision:
2      P0
6      P1
10     P2
14     P3
18     P4
22     P5
26     P6
30     P7
34     P8
38     P9
42    P10
Name: image_preprocessing_pipeline, dtype: object
Max F1 Score:
2      P0
6      P1
10     P2
14     P3
18     P4
22     P5
26     P6
30     P7
34     P8
38     P9
42    P10
Name: image_preprocessing_pipeline, dtype: object
Min Training Time (minutes):
2    P0
Name: image_preprocessing_pipeline, dtype: object
Min Prediction Time (seconds):
18    P4
Name: image_preprocessing_pipeline, dtype: object
Min Peak Memory (MB):
14    P3
Name: image_preprocessing_pipeline, dtype: object

### Inference for ResNet50

* Max AUC: P4, P6
* Max Sensitivity: P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10
* Max Precision: P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10
* Max F1-Score: P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10
* Max Specificity: P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10
* Min Training-Time: P0
* Min Prediction-Time: P4
* Min Peak Memory used: P3

Overall,
1. P4 and P6 attain max AUC score.
2. P0 attains minimum training time.
3. P4 attains minimum prediction time.
4. P3 attains minimum peak memory usage.
5. All pipelines attain the same sensitivity, precision, f1 score and specificity indicating that all pipelines performed the same for these metrics.

In [13]:
vgg16[vgg16['image_preprocessing_pipeline'].isin(['P0', 'P3', 'P4', 'P6'])]

,model,view,image_preprocessing_pipeline,accuracy,auc,sensitivity,precision,specificity,f1_score,training_time_mins,prediction_time_sec,peak_memory_used_MB,parameters
1,VGG16,View_Independent,P0,0.542614,0.503927,0.0,0.0,1.0,0.0,19.597775,10.237638,3285.903564,14715201
13,VGG16,View_Independent,P3,0.542614,0.500000,0.0,0.0,1.0,0.0,21.262187,7.068448,3285.903564,14715201
17,VGG16,View_Independent,P4,0.542614,0.503927,0.0,0.0,1.0,0.0,22.442168,7.656845,3285.903564,14715201
25,VGG16,View_Independent,P6,0.542614,0.503927,0.0,0.0,1.0,0.0,19.049172,6.143839,3285.903564,14715201

### Result for ResNet50
P0, P3, P4 and P6 have the same accuracy, sensitivity, precision, specificity, f1 score and peak memory usage values. P0, P4 and P6 attain identical AUC scores. However, P0 and P6 have the minimum training time with lowest prediction time attained by P6.

All pipelines perform nearly identical with P6 having the lowest prediction time and highest AUC (same as P0, P4) overall.

**Best Image Preprocessing Pipeline for Custom CNN: P6 (Resizing + Grayscale + Median Blur + Normalization)**

## EfficientNet-B0

In [15]:
# EfficientNet-B0 all results
efficientnetb0 = results_df[results_df['model'] == 'EfficientNetB0']

In [16]:
# Get Image preprocessing pipelines with max performances
max_auc_efficientnetb0 = efficientnetb0[efficientnetb0['auc'] == efficientnetb0['auc'].max()]['image_preprocessing_pipeline']
max_sencitivity_efficientnetb0 = efficientnetb0[efficientnetb0['sensitivity'] == efficientnetb0['sensitivity'].max()]['image_preprocessing_pipeline']
max_specificity_efficientnetb0 = efficientnetb0[efficientnetb0['specificity'] == efficientnetb0['specificity'].max()]['image_preprocessing_pipeline']
max_precision_efficientnetb0 = efficientnetb0[efficientnetb0['precision'] == efficientnetb0['precision'].max()]['image_preprocessing_pipeline']
max_f1_efficientnetb0 = efficientnetb0[efficientnetb0['f1_score'] == efficientnetb0['f1_score'].max()]['image_preprocessing_pipeline']

# Get Image Preprocessing Pipelines with least computational costs
min_training_time_efficientnetb0 = efficientnetb0[efficientnetb0['training_time_mins'] == efficientnetb0['training_time_mins'].min()]['image_preprocessing_pipeline']
min_prediction_time_efficientnetb0 = efficientnetb0[efficientnetb0['prediction_time_sec'] == efficientnetb0['prediction_time_sec'].min()]['image_preprocessing_pipeline']
min_peak_memory_efficientnetb0 = efficientnetb0[efficientnetb0['peak_memory_used_MB'] == efficientnetb0['peak_memory_used_MB'].min()]['image_preprocessing_pipeline']

In [17]:
print(f"Max AUC:")
print(max_auc_efficientnetb0)

print(f"Max Sensitivity:")
print(max_sencitivity_efficientnetb0)

print(f"Max Specificity:")
print(max_specificity_efficientnetb0)

print(f"Max Precision:")
print(max_precision_efficientnetb0)

print(f"Max F1 Score:")
print(max_f1_efficientnetb0)

print(f"Min Training Time (minutes):")
print(min_training_time_efficientnetb0)

print(f"Min Prediction Time (seconds):")
print(min_prediction_time_efficientnetb0)

print(f"Min Peak Memory (MB):")
print(min_peak_memory_efficientnetb0)

Max AUC:
35    P8
Name: image_preprocessing_pipeline, dtype: object
Max Sensitivity:
3      P0
7      P1
11     P2
15     P3
19     P4
23     P5
27     P6
31     P7
35     P8
39     P9
43    P10
Name: image_preprocessing_pipeline, dtype: object
Max Specificity:
3      P0
7      P1
11     P2
15     P3
19     P4
23     P5
27     P6
31     P7
35     P8
39     P9
43    P10
Name: image_preprocessing_pipeline, dtype: object
Max Precision:
3      P0
7      P1
11     P2
15     P3
19     P4
23     P5
27     P6
31     P7
35     P8
39     P9
43    P10
Name: image_preprocessing_pipeline, dtype: object
Max F1 Score:
3      P0
7      P1
11     P2
15     P3
19     P4
23     P5
27     P6
31     P7
35     P8
39     P9
43    P10
Name: image_preprocessing_pipeline, dtype: object
Min Training Time (minutes):
3    P0
Name: image_preprocessing_pipeline, dtype: object
Min Prediction Time (seconds):
7    P1
Name: image_preprocessing_pipeline, dtype: object
Min Peak Memory (MB):
43    P10
Name: image_preprocessing_pipeline, dtype: object

### Inference for EfficientNet-B0

* Max AUC: P8
* Max Sensitivity: P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10
* Max Precision: P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10
* Max F1-Score: P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10
* Max Specificity: P0, P1, P2, P3, P4, P5, P6, P7, P8, P9, P10
* Min Training-Time: P0
* Min Prediction-Time: P1
* Min Peak Memory used: P10

Overall,
1. P8 attains max AUC score.
2. P0 attains minimum training time.
3. P1 attains minimum prediction time.
4. P10 attains minimum peak memory usage.
5. All pipelines attain the same sensitivity, precision, f1 score and specificity indicating that all pipelines performed the same for these metrics.

In [18]:
efficientnetb0[efficientnetb0['image_preprocessing_pipeline'].isin(['P0', 'P1', 'P8', 'P10'])]

,model,view,image_preprocessing_pipeline,accuracy,auc,sensitivity,precision,specificity,f1_score,training_time_mins,prediction_time_sec,peak_memory_used_MB,parameters
3,EfficientNetB0,View_Independent,P0,0.542614,0.600354,0.0,0.0,1.0,0.0,17.083932,7.315547,485.064697,4050852
7,EfficientNetB0,View_Independent,P1,0.542614,0.600354,0.0,0.0,1.0,0.0,17.627031,6.109130,485.065918,4050852
35,EfficientNetB0,View_Independent,P8,0.542614,0.607257,0.0,0.0,1.0,0.0,19.364575,7.049481,485.058594,4050852
43,EfficientNetB0,View_Independent,P10,0.542614,0.513886,0.0,0.0,1.0,0.0,18.026278,8.590950,485.056885,4050852

### Result for EfficientNet-B0
P0, P1, P8 and P10 have the same accuracy, sensitivity, precision, specificity, f1 score and peak memory usage values. The training and prediction times of P0, P1, P8 and P10 are nearly identical with very low difference. P8 has the highest AUC score with slightly higher training time and lower prediction time.  

**Best Image Preprocessing Pipeline for EfficientNet-B0: P8 (Resizing + CLAHE with 1-channel Grayscale + Median Blur + Normalization)**

## Conclusion

Best image preprocessing pipelines for the selected CNN architectures for breast cancer classification using CBIS-DDSM dataset are as follows:

* **Custom CNN: P2 *(Resizing + CLAHE with 1-channel Grayscale + Normalization)***
* **VGG16: P2 *(Resizing + CLAHE with 1-channel Grayscale + Normalization)***
* **ResNet50: P6 *(Resizing + Grayscale + Median Blur + Normalization)***
* **EfficientNet-B0: P8 *(Resizing + CLAHE with 1-channel Grayscale + Median Blur + Normalization)***